#version: '3.5'
#name: 'popote'

# Services
services:

  # base de donnee Service :
  mariadb:
    container_name: popote_mariadb
    restart: on-failure
    build: 
      context: .
      dockerfile: mariadb/dockerfile
    ports:
      - 3306:3306
    networks:
      - popote_interne

  # backend Service : serveur node
  backend:
    container_name: popote_backend
    restart: on-failure
    build: 
      context: .
      dockerfile: serverNode/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mariadb
    networks:
      - popote_interne

  # frontend Service : VueJS
  frontend:
    container_name: popote_frontend
    restart: on-failure
    build: 
      context: .
      dockerfile: popote/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend
    networks:
      - popote_interne
      - popote_externe

# configuration reseau
networks:
  popote_interne:
    driver: bridge
  popote_externe:
    external: true
