
name: Deployment_popote_dev

concurrency: development

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-ubuntu-latest
    environment: development
    steps: 
      - name: stop execution container
        run: ssh -p 443 bruno@popote.zapto.org 'cd /home/bruno/popote_vueJS_K8S && docker-compose stop'
      - name: charger le deploiement
        run: ssh -p 443 bruno@popote.zapto.org 'cd /home/bruno/popote_vueJS_K8S && git pull origin main'
      - name: executer le deploiement
        run: ssh -p 443 bruno@popote.zapto.org 'cd /home/bruno/popote_vueJS_K8S && docker-compose up --build'
