
name: Deployment_popote_dev

concurrency: development

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-ubuntu-latest
    environment: development
    steps: 
      - name: deploy
        # etapes du deploiement
        